import {Html, Head, Main, NextScript} from "next/document"

export default function Document() {
  return (
    <Html>
      <Head>
        <meta name="description" content="Tienda de ventas de instrumentos musicales" />
        <title>Tienda de Instrumentos Musicales</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Main/>
        <NextScript/>
      </body>
    </Html>
  )
}

